name: CI

on:
  push:
    branches:
      - master

jobs:
  prepare_version:
    name: Prepare Version
    runs-on: ubuntu-18.04
    if: "!contains(github.actor, 'process-engine-ci') || contains(github.actor, 'admin')"

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - name: Show Actor
      run: echo $ACTOR
      env:
        ACTOR: ${{ github.actor }}

    - name: Install npm Dependencies
      run: npm ci

    - name: Adjust Version
      run: |
        ./node_modules/.bin/ci_tools prepare-version --allow-dirty-workdir

    - name: Stash package.json
      uses: actions/upload-artifact@master
      with:
        name: package_json
        path: package.json

  build:
    name: Build Extension
    needs: prepare_version
    if: "!contains(github.actor, 'process-engine-ci') || contains(github.actor, 'admin')"
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1

      - name: Unstash package.json
        uses: actions/download-artifact@master
        with:
          name: package_json
          path: "."

      - name: Install npm Dependencies
        run: |
          npm ci

      - name: Build Extension
        run: |
          npm run build
          mkdir release
          mv charon2-goto-*.vsix release/

      - name: Stash Extension
        uses: actions/upload-artifact@master
        with:
          name: release
          path: release/

  commit_and_tag_version:
    name: "Commit & Tag Version"
    needs: build
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - name: Unstash package.json
      uses: actions/download-artifact@master
      with:
        name: package_json
        path: "."

    - name: Install CI Tools
      run: npm ci

    - name: Commit and Tag
      run: |
        ./node_modules/.bin/ci_tools commit-and-tag-version --only-on-primary-branches
        ./node_modules/.bin/ci_tools update-github-release --only-on-primary-branches --use-title-and-text-from-git-tag
      env:
        GH_USER: ${{ secrets.GH_USER }}
        GH_TOKEN: ${{ secrets.GH_TOKEN }}

  publish:
    name: "Publish Extension"
    needs: commit_and_tag_version
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - name: Install CI Tools
      run: npm ci

    - name: Publish
      run: npm run publish -- -p $VSCODE_TOKEN
      env:
        VSCODE_TOKEN: ${{ secrets.VSCODE_TOKEN }}

  publish_github:
    name: "Publish GitHub Release"
    needs: publish
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Unstash package.json
        uses: actions/download-artifact@master
        with:
          name: package_json
          path: "."

      - name: Unstash Extensioon
        uses: actions/download-artifact@master
        with:
          name: release
          path: "."

      - name: Install CI Tools
        run: npm ci

      - name: Upload to GitHub
        run: |
          ./node_modules/.bin/ci_tools update-github-release \
                                --assets charon2-goto-*.vsix
        env:
          GH_USER: ${{ secrets.GH_USER }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
